package juegodados;

import java.util.Random;

public class FrmJuego extends javax.swing.JFrame {

    private int lanzamientos;
    private int cenas;

    //Declarar los objetos de la clase dado 
    private Dado dado1, dado2;

    //Obsjero para generar la aleatoriedad
    private Random r;

    public FrmJuego() {
        initComponents();

        //Instanciar los objetos Dado
        dado1 = new Dado();
        dado2 = new Dado();

        //Instanciar random
        r = new Random();

        //Iniciar los contadores
        lanzamientos = 0;
        cenas = 0;

    }

    private void mostrarContadores() {
        LblLanzamientos.setText(String.valueOf(lanzamientos));
        LblCenas.setText(String.valueOf(cenas));
        mostrarContadores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblDado1 = new javax.swing.JLabel();
        LblDado2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LblLanzamientos = new javax.swing.JLabel();
        LblCenas = new javax.swing.JLabel();
        BtnIniciar = new javax.swing.JButton();
        BtnLanzar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblDado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1.jpg"))); // NOI18N

        LblDado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2.jpg"))); // NOI18N

        jLabel3.setText("Lanzamientos");

        jLabel4.setText("Cenas");

        LblLanzamientos.setBackground(new java.awt.Color(102, 102, 102));
        LblLanzamientos.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        LblLanzamientos.setForeground(new java.awt.Color(0, 255, 255));
        LblLanzamientos.setText("0");
        LblLanzamientos.setOpaque(true);

        LblCenas.setBackground(new java.awt.Color(102, 102, 102));
        LblCenas.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        LblCenas.setForeground(new java.awt.Color(0, 255, 255));
        LblCenas.setText("0");
        LblCenas.setOpaque(true);

        BtnIniciar.setText("Iniciar");
        BtnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIniciarActionPerformed(evt);
            }
        });

        BtnLanzar.setText("Lanzar");
        BtnLanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLanzarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(LblDado1)
                .addGap(18, 18, 18)
                .addComponent(LblDado2)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(LblLanzamientos)))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblCenas)
                        .addContainerGap(204, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(BtnIniciar)
                .addGap(40, 40, 40)
                .addComponent(BtnLanzar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblLanzamientos)
                            .addComponent(LblCenas)))
                    .addComponent(LblDado1)
                    .addComponent(LblDado2))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnIniciar)
                    .addComponent(BtnLanzar))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIniciarActionPerformed
        //Iniciar los contadores
        lanzamientos = 0;
        cenas = 0;
        mostrarContadores();
    }//GEN-LAST:event_BtnIniciarActionPerformed

    private void BtnLanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLanzarActionPerformed

        dado1.lanzar(r);
        dado1.mostrar(LblDado1);

        dado2.lanzar(r);
        dado2.mostrar(LblDado2);

        //Actualizar los contadores
        lanzamientos++;
        if (dado1.getNumero() + dado2.getNumero() >= 11) {
            cenas++;
        }

        mostrarContadores();
    }//GEN-LAST:event_BtnLanzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIniciar;
    private javax.swing.JButton BtnLanzar;
    private javax.swing.JLabel LblCenas;
    private javax.swing.JLabel LblDado1;
    private javax.swing.JLabel LblDado2;
    private javax.swing.JLabel LblLanzamientos;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
